- id: '1723790105072'
  alias: Automatisches Proteinefalten
  description: ''
  triggers:
  - type: power
    device_id: 21b7a24751e24219971550406bbc70f0
    entity_id: e921d4f2a64dd07795908df990f7d8c6
    domain: sensor
    below: -169
    for:
      hours: 0
      minutes: 2
      seconds: 0
    trigger: device
  conditions: []
  actions:
  - sequence:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.rechenkiste
    - action: shell_command.sleep_for_90sec
      metadata: {}
      data: {}
      enabled: false
    - action: shell_command.turn_off_both_gpus
      metadata: {}
      data: {}
      enabled: false
    - action: input_select.select_option
      metadata: {}
      data:
        option: No GPU
      target:
        entity_id: input_select.proteinfaltungszustand
      enabled: false
  mode: single
- id: '1725316799249'
  alias: Stromsparend; Abends stand by Strom sparen
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 53cc89dcfd6590bf1279abc2f29078a7
    entity_id: 1012241a0e41dd92593dd753958e8e63
    domain: switch
  mode: single
- id: '1725316915877'
  alias: Stromsparend durch passiven Energieverbrauch
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - type: turn_off
    device_id: b7dcc3a6353f56745e22e7b46885592b
    entity_id: 4655fb1110b0969fba3f536e48361e9a
    domain: switch
  mode: single
- id: '1725317004191'
  alias: Start Energy with Sun light
  description: 'Jetzt fängt Solar langsam an '
  trigger:
  - platform: time
    at: 08:30:00
  condition: []
  action:
  - type: turn_on
    device_id: 53cc89dcfd6590bf1279abc2f29078a7
    entity_id: 1012241a0e41dd92593dd753958e8e63
    domain: switch
  mode: single
- id: '1725401123579'
  alias: Wieder anschalten
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - type: turn_on
    device_id: b7dcc3a6353f56745e22e7b46885592b
    entity_id: 4655fb1110b0969fba3f536e48361e9a
    domain: switch
  mode: single
- id: '1725436842778'
  alias: Proteinfaltung ausschalten
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '5'
  - platform: time_pattern
    minutes: '10'
  - platform: time_pattern
    minutes: '15'
  - platform: time_pattern
    minutes: '20'
  - platform: time_pattern
    minutes: '25'
  - platform: time_pattern
    minutes: '30'
  - platform: time_pattern
    minutes: '35'
  - platform: time_pattern
    minutes: '40'
  - platform: time_pattern
    minutes: '45'
  - platform: time_pattern
    minutes: '50'
  - platform: time_pattern
    minutes: '55'
  - platform: time_pattern
    minutes: '0'
  condition:
  - condition: and
    conditions:
    - condition: state

automation:
  - alias: "Shell Command via Input Button"
    trigger:
      platform: state
      entity_id: input_button.shell_command_button
      to: "pressed"
    action:
      service: shell_command.befehl_ausfuehren

      entity_id: input_select.proteinfaltungszustand
      state: No GPU
      for:
        hours: 0
        minutes: 5
        seconds: 0
      enabled: true
    - type: is_power
      condition: device
      device_id: 21b7a24751e24219971550406bbc70f0
      entity_id: e921d4f2a64dd07795908df990f7d8c6
      domain: sensor
      above: 0
    - condition: sun
      before: sunset
      after: sunrise
  action:
  - sequence:
    - action: shell_command.turn_off_both_gpus
      metadata: {}
      data: {}
    - action: input_select.select_option
      metadata: {}
      data:
        option: No GPU
      target:
        entity_id: input_select.proteinfaltungszustand
    - action: switch.turn_off
      target:
        entity_id: switch.rechenkiste
      data: {}
  mode: parallel
  max: 10
- id: '1726138108434'
  alias: Camping Powerstation aufladen
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 21b7a24751e24219971550406bbc70f0
    entity_id: e921d4f2a64dd07795908df990f7d8c6
    domain: sensor
    below: 0
    for:
      hours: 0
      minutes: 0
      seconds: 20
  condition: []
  action:
  - type: turn_on
    device_id: cb1c89d23929477b134967b5395c3bfc
    entity_id: 41d5b9c419c2317443cceb924ddbfb73
    domain: switch
  mode: single
- id: '1726138152540'
  alias: Camping Powerstation ausschalten
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 21b7a24751e24219971550406bbc70f0
    entity_id: e921d4f2a64dd07795908df990f7d8c6
    domain: sensor
    above: 0
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - type: turn_off
    device_id: cb1c89d23929477b134967b5395c3bfc
    entity_id: 41d5b9c419c2317443cceb924ddbfb73
    domain: switch
  mode: single
